// ============================================
// PERGUNTAS DA FORCA - COPA 2026
// 1000 PERGUNTAS COMPLETAS
// ATUALIZADO EM 26/06/2026
// ============================================

const TODAS_PERGUNTAS = [

    // ==========================================
    // 1. CAMPEÕES MUNDIAIS (10)
    // ==========================================
    { palavra: "BRASIL", dicas: ["País com 5 títulos mundiais", "Pentacampeão em 2002", "País do futebol arte"] },
    { palavra: "ALEMANHA", dicas: ["4 títulos mundiais", "Campeã em 2014", "País da seleção alemã"] },
    { palavra: "ITALIA", dicas: ["4 títulos mundiais", "Campeã em 2006", "País da Squadra Azzurra"] },
    { palavra: "ARGENTINA", dicas: ["3 títulos mundiais", "Campeã em 2022", "País de Messi"] },
    { palavra: "FRANCA", dicas: ["2 títulos mundiais", "Campeã em 2018", "País de Mbappé"] },
    { palavra: "URUGUAI", dicas: ["2 títulos mundiais", "Campeão em 1950", "País do Maracanazo"] },
    { palavra: "INGLATERRA", dicas: ["1 título mundial", "Campeã em 1966", "País da Premier League"] },
    { palavra: "ESPANHA", dicas: ["1 título mundial", "Campeã em 2010", "País do tiki-taka"] },
    { palavra: "CROACIA", dicas: ["Vice-campeã em 2018", "Terceiro lugar em 2022", "País de Modric"] },
    { palavra: "HOLANDA", dicas: ["Vice-campeã em 2010", "Terceiro lugar em 2014", "País da Laranja Mecânica"] },

    // ==========================================
    // 2. JOGADORES BRASILEIROS (50)
    // ==========================================
    { palavra: "PELE", dicas: ["Rei do futebol", "3 títulos mundiais", "Maior jogador da história"] },
    { palavra: "RONALDO", dicas: ["Fenômeno", "Campeão em 2002", "Artilheiro da Copa de 2002"] },
    { palavra: "NEYMAR", dicas: ["Camisa 10 do Brasil", "Maior artilheiro da seleção", "Revelado pelo Santos"] },
    { palavra: "RONALDINHO", dicas: ["Campeão em 2002", "Bruxo", "Melhor do mundo em 2005"] },
    { palavra: "ROMARIO", dicas: ["Campeão em 1994", "Base do Vasco", "Baixinho"] },
    { palavra: "RIVALDO", dicas: ["Campeão em 2002", "Pernambucano", "Melhor do mundo em 1999"] },
    { palavra: "GARRINCHA", dicas: ["Campeão em 1962", "Anjo das pernas tortas", "Jogou no Botafogo"] },
    { palavra: "ZICO", dicas: ["Galinho", "Maior ídolo do Flamengo", "Gênio do futebol"] },
    { palavra: "ROBERTO CARLOS", dicas: ["Lateral esquerdo", "Campeão em 2002", "Famoso pela falta"] },
    { palavra: "CAFU", dicas: ["Lateral direito", "Campeão em 1994 e 2002", "Capitão do penta"] },
    { palavra: "ROBERTO DINAMITE", dicas: ["Maior ídolo do Vasco", "Artilheiro histórico do clube", "Campeão brasileiro de 1974"] },
    { palavra: "TOSTAO", dicas: ["Campeão do mundo 1970", "Meia do Cruzeiro", "Grande jogador da seleção"] },
    { palavra: "GERSON", dicas: ["Canhotinha de ouro", "Campeão do mundo 1970", "Meia do Flamengo"] },
    { palavra: "FALCAO", dicas: ["Rei de Roma", "Jogou no Internacional", "Grande meio-campista"] },
    { palavra: "SOCRATES", dicas: ["Médico e jogador", "Capitão da seleção de 1982", "Ídolo do Corinthians"] },
    { palavra: "DIDI", dicas: ["Folha seca", "Campeão do mundo 1958 e 1962", "Meia do Botafogo"] },
    { palavra: "NILTON SANTOS", dicas: ["Lateral esquerdo", "Campeão do mundo 1958 e 1962", "Ídolo do Botafogo"] },
    { palavra: "ZAGALLO", dicas: ["Ponta-esquerda", "Campeão do mundo 1958 e 1962", "Único com 4 Copas no currículo"] },
    { palavra: "LEAO", dicas: ["Goleiro", "Campeão do mundo 1970", "Ídolo do Palmeiras"] },
    { palavra: "JAIRZINHO", dicas: ["Ponta-direita", "Campeão do mundo 1970", "Fez gols em todos os jogos da Copa"] },
    { palavra: "RIVELINO", dicas: ["Meia", "Campeão do mundo 1970", "Destaque da seleção brasileira"] },
    { palavra: "BEBETO", dicas: ["Atacante", "Campeão do mundo 1994", "Famoso pela comemoração do bebê"] },
    { palavra: "BRANCO", dicas: ["Lateral esquerdo", "Campeão do mundo 1994", "Famoso pelas faltas decisivas"] },
    { palavra: "DUNGA", dicas: ["Volante", "Campeão do mundo 1994", "Capitão do tetra"] },
    { palavra: "TAFFAREL", dicas: ["Goleiro", "Campeão do mundo 1994", "Ídolo do Internacional"] },
    { palavra: "CLODOALDO", dicas: ["Volante", "Campeão do mundo 1970", "Ídolo do Santos"] },
    { palavra: "PEPE", dicas: ["Atacante", "Campeão do mundo 1962", "Ídolo do Santos"] },
    { palavra: "GILMAR", dicas: ["Goleiro", "Campeão do mundo 1958 e 1962", "Ídolo do Santos"] },
    { palavra: "MENGALVIO", dicas: ["Meia", "Campeão do mundo 1962", "Ídolo do Santos"] },
    { palavra: "ZITO", dicas: ["Volante", "Campeão do mundo 1962", "Ídolo do Santos"] },
    { palavra: "ORLANDO", dicas: ["Zagueiro", "Campeão do mundo 1962", "Ídolo do Santos"] },
    { palavra: "AMARILDO", dicas: ["Atacante", "Campeão do mundo 1962", "Ídolo do Botafogo"] },
    { palavra: "JUNIOR", dicas: ["Lateral esquerdo", "Destaque da Copa de 1982", "Ídolo do Flamengo"] },
    { palavra: "LEANDRO", dicas: ["Lateral direito", "Destaque da Copa de 1982", "Ídolo do Flamengo"] },
    { palavra: "ADILIO", dicas: ["Meia habilidoso", "Campeão do mundo com o Flamengo em 1981", "Ídolo do Flamengo"] },
    { palavra: "VINI JR", dicas: ["Atacante do Real Madrid", "Campeão da Champions League", "Protagonista da seleção"] },
    { palavra: "ENDRICK", dicas: ["Jovem promessa", "Joga no Real Madrid", "Revelação do Palmeiras"] },
    { palavra: "ESTEVAO", dicas: ["Jovem promessa", "Joga no Palmeiras", "Grande destaque"] },
    { palavra: "RODRYGO", dicas: ["Atacante do Real Madrid", "Conhecido como 'Raio'", "Menino da Vila"] },
    { palavra: "MARTINELLI", dicas: ["Atacante do Arsenal", "Revelação", "Brasileiro"] },
    { palavra: "GABRIEL JESUS", dicas: ["Atacante do Arsenal", "Revelado pelo Palmeiras", "Campeão Brasileiro"] },
    { palavra: "RICHARLISON", dicas: ["Atacante do Tottenham", "Revelado pelo Fluminense", "Artilheiro"] },
    { palavra: "ANTONY", dicas: ["Atacante do Manchester United", "Revelado pelo São Paulo", "Dribles"] },
    { palavra: "RAPHINHA", dicas: ["Atacante do Barcelona", "Revelado pelo Avaí", "Velocidade"] },
    { palavra: "PAQUETA", dicas: ["Meia do West Ham", "Revelado pelo Flamengo", "Criativo"] },
    { palavra: "GERSON", dicas: ["Volante do Flamengo", "Conhecido como Coringa", "Campeão da Libertadores"] },
    { palavra: "ARTHUR", dicas: ["Meia ex-Fluminense", "Revelado em Xerém", "Passagem pela Europa"] },
    { palavra: "FABINHO", dicas: ["Volante do Al-Ittihad", "Revelado pelo Paulínia e Fluminense", "Campeão da Champions"] },
    { palavra: "ALISSON", dicas: ["Goleiro do Liverpool", "Revelado pelo Internacional", "Melhor goleiro do mundo"] },
    { palavra: "EDERSON", dicas: ["Goleiro do Manchester City", "Revelado pelo Benfica", "Melhor goleiro"] },

    // ==========================================
    // 3. JOGADORES ARGENTINOS (20)
    // ==========================================
    { palavra: "MESSI", dicas: ["8 Bolas de Ouro", "Campeão em 2022", "Ídolo do Barcelona"] },
    { palavra: "MARADONA", dicas: ["Campeão em 1986", "Mão de Deus", "Ídolo do Napoli"] },
    { palavra: "DI MARIA", dicas: ["Gol na final de 2022", "Joga no Benfica", "Ponta esquerda"] },
    { palavra: "AGUERO", dicas: ["Artilheiro do Manchester City", "Ex-genro de Maradona", "Se aposentou por problemas no coração"] },
    { palavra: "BATISTUTA", dicas: ["Segundo maior artilheiro da seleção", "Ídolo da Fiorentina", "Apelidado de 'Batigol'"] },
    { palavra: "DYBALA", dicas: ["Atacante da Roma", "Revelado pelo Palermo", "Camisa 10"] },
    { palavra: "LAUTARO", dicas: ["Atacante da Inter", "Artilheiro", "Campeão da Serie A"] },
    { palavra: "MAC ALLISTER", dicas: ["Meia do Liverpool", "Campeão do mundo 2022", "Revelado pelo Argentinos Juniors"] },
    { palavra: "ENZO FERNANDEZ", dicas: ["Meia do Chelsea", "Campeão do mundo 2022", "Revelado pelo River Plate"] },
    { palavra: "JULIAN ALVAREZ", dicas: ["Atacante do Atlético de Madrid", "Campeão do mundo 2022", "Revelado pelo River Plate"] },
    { palavra: "OTAMENDI", dicas: ["Zagueiro do Benfica", "Campeão do mundo 2022", "Passagem pelo Manchester City"] },
    { palavra: "ROMERO", dicas: ["Zagueiro do Tottenham", "Campeão do mundo 2022", "Revelado pelo Belgrano"] },
    { palavra: "MARTINEZ", dicas: ["Goleiro do Aston Villa", "Campeão do mundo 2022", "Herói da final"] },
    { palavra: "DE PAUL", dicas: ["Meia do Atlético de Madrid", "Campeão do mundo 2022", "Revelado pelo Racing"] },
    { palavra: "PAREDES", dicas: ["Volante da Roma", "Campeão do mundo 2022", "Revelado pelo Boca Juniors"] },
    { palavra: "ZANETTI", dicas: ["Lateral da Inter", "Ídolo", "Jogou por muitos anos na Itália"] },
    { palavra: "CAMBIASSO", dicas: ["Volante", "Passagem pela Inter", "Seleção Argentina"] },
    { palavra: "MASCERANO", dicas: ["Volante", "Jogou no Barcelona", "Seleção Argentina"] },
    { palavra: "TEVEZ", dicas: ["Atacante", "Jogou no Corinthians", "Fenômeno"] },
    { palavra: "HIGUAIN", dicas: ["Atacante", "Passagem pelo Real Madrid", "Seleção Argentina"] },

    // ==========================================
    // 4. JOGADORES EUROPEUS (30)
    // ==========================================
    { palavra: "CRISTIANO RONALDO", dicas: ["5 Champions", "Maior artilheiro da história", "Ídolo do Real Madrid"] },
    { palavra: "MBAPPE", dicas: ["Campeão em 2018", "Velocidade", "Joga no Real Madrid"] },
    { palavra: "DE BRUYNE", dicas: ["Meia do Manchester City", "Melhor passador do mundo", "Belga"] },
    { palavra: "HAALAND", dicas: ["Atacante do Manchester City", "Artilheiro na Premier League", "Norueguês"] },
    { palavra: "BENZEMA", dicas: ["Bola de Ouro 2022", "Jogou no Real Madrid", "Francês"] },
    { palavra: "MODRIC", dicas: ["Bola de Ouro 2018", "Meia do Real Madrid", "Croata"] },
    { palavra: "LEWANDOWSKI", dicas: ["Artilheiro do Bayern", "Joga no Barcelona", "Polonês"] },
    { palavra: "INIESTA", dicas: ["Autor do gol do título da Copa de 2010", "Ídolo do Barcelona", "Meia genial espanhol"] },
    { palavra: "KANE", dicas: ["Atacante do Bayern", "Artilheiro da seleção inglesa", "Camisa 9"] },
    { palavra: "NEUER", dicas: ["Goleiro da Alemanha", "Campeão em 2014", "Goleiro líbero"] },
    { palavra: "KROOS", dicas: ["Meia da Alemanha", "Campeão do mundo 2014", "Aposentou-se no Real Madrid"] },
    { palavra: "MULLER", dicas: ["Atacante da Alemanha", "Campeão do mundo 2014", "Joga no Bayern"] },
    { palavra: "GNABRY", dicas: ["Atacante da Alemanha", "Joga no Bayern", "Campeão"] },
    { palavra: "RUDIGER", dicas: ["Zagueiro da Alemanha", "Joga no Real Madrid", "Defensor"] },
    { palavra: "VAN DIJK", dicas: ["Zagueiro do Liverpool", "Holandês", "Melhor zagueiro do mundo"] },
    { palavra: "DE JONG", dicas: ["Meia do Barcelona", "Holandês", "Passagem pelo Ajax"] },
    { palavra: "GRIEZMANN", dicas: ["Atacante do Atlético de Madrid", "Campeão do mundo 2018", "Francês"] },
    { palavra: "POGBA", dicas: ["Meia da França", "Campeão do mundo 2018", "Jogou no Manchester United"] },
    { palavra: "KANTE", dicas: ["Volante da França", "Campeão do mundo 2018", "Jogou no Leicester"] },
    { palavra: "SANCHO", dicas: ["Atacante inglês", "Joga no Manchester United", "Velocidade"] },
    { palavra: "BELLINGHAM", dicas: ["Meia do Real Madrid", "Inglês", "Jovem talento"] },
    { palavra: "SAKA", dicas: ["Atacante do Arsenal", "Inglês", "Revelação"] },
    { palavra: "FODEN", dicas: ["Meia do Manchester City", "Inglês", "Campeão da Premier"] },
    { palavra: "RICE", dicas: ["Volante do Arsenal", "Inglês", "Capitão"] },
    { palavra: "DONNARUMMA", dicas: ["Goleiro do PSG", "Italiano", "Campeão da Euro 2020"] },
    { palavra: "BARELLA", dicas: ["Meia da Inter", "Italiano", "Campeão da Euro 2020"] },
    { palavra: "CHIESA", dicas: ["Atacante da Juventus", "Italiano", "Campeão da Euro 2020"] },
    { palavra: "VERRATTI", dicas: ["Volante do Al-Arabi", "Italiano", "Campeão da Euro 2020"] },
    { palavra: "IMMOBILE", dicas: ["Atacante da Besiktas", "Italiano", "Campeão da Euro 2020"] },
    { palavra: "INSIGNE", dicas: ["Atacante ex-Napoli", "Italiano", "Campeão da Euro 2020"] },

    // ==========================================
    // 5. JOGADORES AFRICANOS E OUTROS (20)
    // ==========================================
    { palavra: "SALAH", dicas: ["Atacante do Liverpool", "Egípcio", "Campeão da Champions 2019"] },
    { palavra: "MANE", dicas: ["Atacante do Al-Nassr", "Senegalês", "Campeão da Champions"] },
    { palavra: "MAHREZ", dicas: ["Atacante do Al-Ahli", "Argelino", "Campeão da Champions"] },
    { palavra: "OSIMHEN", dicas: ["Atacante do Napoli", "Nigeriano", "Artilheiro da Serie A"] },
    { palavra: "HAKIMI", dicas: ["Lateral do PSG", "Marroquino", "Velocidade"] },
    { palavra: "ZIYECH", dicas: ["Meia do Galatasaray", "Marroquino", "Drible"] },
    { palavra: "BONO", dicas: ["Goleiro do Al-Hilal", "Marroquino", "Destaque na Copa de 2022"] },
    { palavra: "KESSIE", dicas: ["Meia do Al-Ahli", "Marfinense", "Passagem pelo Barcelona"] },
    { palavra: "PEPE", dicas: ["Zagueiro ex-Porto", "Português", "Campeão da Euro 2016"] },
    { palavra: "CARRASCO", dicas: ["Atacante do Al-Shabab", "Belga", "Drible"] },
    { palavra: "NAVAS", dicas: ["Goleiro ex-PSG", "Costarriquenho", "Destaque na Copa de 2014"] },
    { palavra: "CAICEDO", dicas: ["Volante do Chelsea", "Equatoriano", "Revelação"] },
    { palavra: "MONTANO", dicas: ["Atacante", "Colombiano", "Passagem pelo Seattle"] },
    { palavra: "DIAZ", dicas: ["Atacante do Liverpool", "Colombiano", "Velocidade"] },
    { palavra: "SINISTERRA", dicas: ["Atacante do Bournemouth", "Colombiano", "Drible"] },
    { palavra: "QUINTERO", dicas: ["Meia do Racing", "Colombiano", "Criativo"] },
    { palavra: "BORJA", dicas: ["Atacante do River Plate", "Colombiano", "Artilheiro"] },
    { palavra: "SAMPAIO", dicas: ["Defensor", "Peruano", "Destaque"] },
    { palavra: "YOTUN", dicas: ["Meia do Sporting Cristal", "Peruano", "Capitão"] },
    { palavra: "GUERRERO", dicas: ["Atacante histórico", "Peruano", "Artilheiro"] },

    // ==========================================
    // 6. ANOS DAS COPAS (10)
    // ==========================================
    { palavra: "1930", dicas: ["Primeira Copa do Mundo", "Uruguai campeão", "Sede no Uruguai"] },
    { palavra: "1958", dicas: ["Brasil campeão", "Pelé estreou com 17 anos", "Sede na Suécia"] },
    { palavra: "1970", dicas: ["Brasil tricampeão", "Pelé e Garrincha", "Sede no México"] },
    { palavra: "1994", dicas: ["Brasil tetracampeão", "Romário artilheiro", "Sede nos EUA"] },
    { palavra: "2002", dicas: ["Brasil pentacampeão", "Ronaldo artilheiro", "Sede na Coreia/Japão"] },
    { palavra: "2006", dicas: ["Itália campeã", "Zidane cabeceou Materazzi", "Sede na Alemanha"] },
    { palavra: "2010", dicas: ["Espanha campeã", "Iniesta herói", "Sede na África do Sul"] },
    { palavra: "2014", dicas: ["Alemanha campeã", "7 a 1 no Brasil", "Sede no Brasil"] },
    { palavra: "2018", dicas: ["França campeã", "Mbappé revelação", "Sede na Rússia"] },
    { palavra: "2022", dicas: ["Argentina campeã", "Messi campeão", "Sede no Catar"] },

    // ==========================================
    // 7. SELEÇÕES E APELIDOS (15)
    // ==========================================
    { palavra: "CANARINHO", dicas: ["Apelido da seleção brasileira", "Cores amarelo e azul", "5 títulos mundiais"] },
    { palavra: "ALBICELESTE", dicas: ["Apelido da Argentina", "Cores branco e azul", "Messi e Maradona"] },
    { palavra: "TIKI TAKA", dicas: ["Estilo de jogo espanhol", "Muitos passes", "Campeã em 2010"] },
    { palavra: "LES BLEUS", dicas: ["Apelido da seleção da França", "Camisa azul", "Bicampeã mundial (1998 e 2018)"] },
    { palavra: "AZURRA", dicas: ["Apelido da Itália", "Camisa azul", "4 títulos mundiais"] },
    { palavra: "MANNSCHAFT", dicas: ["Apelido da Alemanha", "Camisa branca", "4 títulos mundiais"] },
    { palavra: "FENÔMENO", dicas: ["Apelido de Ronaldo", "Pentacampeão", "Atacante"] },
    { palavra: "BRUXO", dicas: ["Apelido de Ronaldinho", "Campeão em 2002", "Sorriso"] },
    { palavra: "REI", dicas: ["Apelido de Pelé", "Maior da história", "3 títulos"] },
    { palavra: "GALINHO", dicas: ["Apelido de Zico", "Ídolo do Flamengo", "Artilheiro"] },
    { palavra: "ANIMAL", dicas: ["Apelido de Edmundo", "Atacante", "Vasco"] },
    { palavra: "DIVINO", dicas: ["Apelido de Ademir da Guia", "Palmeiras", "Meia"] },
    { palavra: "A CANARINHA", dicas: ["Apelido da seleção brasileira feminina", "Marta", "Destaque"] },
    { palavra: "FURIA VERMELHA", dicas: ["Apelido da seleção da Espanha", "Camisa vermelha", "Campeã em 2010"] },
    { palavra: "GUERREIROS", dicas: ["Apelido da seleção de Gana", "África", "Destaque"] },

    // ==========================================
    // 8. ESTÁDIOS E CIDADES (25)
    // ==========================================
    { palavra: "MARACANA", dicas: ["Estádio do Rio de Janeiro", "Final de 1950", "Estádio do Brasil"] },
    { palavra: "WEMBLEY", dicas: ["Estádio de Londres", "Final de 1966", "Inglaterra"] },
    { palavra: "CENTENARIO", dicas: ["Estádio de Montevidéu", "Primeira final de Copa em 1930", "Uruguai"] },
    { palavra: "BERNABEU", dicas: ["Estádio do Real Madrid", "Espanha", "Estádio famoso"] },
    { palavra: "CAMP NOU", dicas: ["Estádio do Barcelona", "Espanha", "Maior da Europa"] },
    { palavra: "AZTECA", dicas: ["Estádio do México", "Final de 1970", "Final de 1986"] },
    { palavra: "MINEIRAO", dicas: ["Estádio de Belo Horizonte", "7 a 1 da Alemanha", "Brasil"] },
    { palavra: "FONTENOVA", dicas: ["Estádio de Salvador", "Copa de 2014", "Brasil"] },
    { palavra: "BEIRA RIO", dicas: ["Estádio do Internacional", "Porto Alegre", "Brasil"] },
    { palavra: "MORUMBI", dicas: ["Estádio do São Paulo", "São Paulo", "Brasil"] },
    { palavra: "ALLIANZ", dicas: ["Estádio do Bayern", "Alemanha", "Moderno"] },
    { palavra: "SAN SIRO", dicas: ["Estádio de Milão", "Itália", "Inter e Milan"] },
    { palavra: "LUZ", dicas: ["Estádio do Benfica", "Portugal", "Histórico"] },
    { palavra: "DRAGAO", dicas: ["Estádio do Porto", "Portugal", "Moderno"] },
    { palavra: "OLIMPICO", dicas: ["Estádio de Berlim", "Alemanha", "Histórico"] },
    { palavra: "ARENA FONTE NOVA", dicas: ["Estádio de Salvador", "Copa 2014", "Brasil"] },
    { palavra: "ARENA PERNAMBUCO", dicas: ["Estádio de Recife", "Copa 2014", "Brasil"] },
    { palavra: "ARENA DAS DUNAS", dicas: ["Estádio de Natal", "Copa 2014", "Brasil"] },
    { palavra: "ARENA AMAZONIA", dicas: ["Estádio de Manaus", "Copa 2014", "Brasil"] },
    { palavra: "PACAEMBU", dicas: ["Estádio de São Paulo", "Histórico", "Brasil"] },
    { palavra: "SERRA DOURADA", dicas: ["Estádio de Goiânia", "Histórico", "Brasil"] },
    { palavra: "CASTELEAO", dicas: ["Estádio de Fortaleza", "Copa 2014", "Brasil"] },
    { palavra: "ARENA DA BAIXADA", dicas: ["Estádio de Curitiba", "Athletico Paranaense", "Brasil"] },
    { palavra: "ARENA DO GREMIO", dicas: ["Estádio de Porto Alegre", "Grêmio", "Brasil"] },
    { palavra: "ARENA CORINTHIANS", dicas: ["Estádio de São Paulo", "Corinthians", "Copa 2014"] },

    // ==========================================
    // 9. TÉCNICOS FAMOSOS (15)
    // ==========================================
    { palavra: "ZAGALLO", dicas: ["Técnico do tri", "Campeão em 1970", "Único com 4 copas no currículo"] },
    { palavra: "PARREIRA", dicas: ["Técnico do tetra", "Campeão em 1994", "Brasileiro"] },
    { palavra: "SCALONI", dicas: ["Técnico da Argentina", "Campeão em 2022", "Revelação"] },
    { palavra: "DESCHAMPS", dicas: ["Técnico da França", "Campeão em 2018", "Volante"] },
    { palavra: "LOW", dicas: ["Técnico da Alemanha", "Campeão em 2014", "Substituto de Klinsmann"] },
    { palavra: "GUARDIOLA", dicas: ["Técnico do Manchester City", "Espanhol", "Tiki-taka"] },
    { palavra: "KLOPP", dicas: ["Técnico multicampeão", "Alemão", "Heavy metal football"] },
    { palavra: "MOURINHO", dicas: ["Técnico português", "Special One", "Treinou Chelsea e Real"] },
    { palavra: "SCOLARI", dicas: ["Técnico do penta", "Felipão", "Campeão em 2002"] },
    { palavra: "TITE", dicas: ["Comandou o Brasil nas Copas de 2018 e 2022", "Multi-campeão pelo Corinthians", "Gaúcho"] },
    { palavra: "ARTUR JORGE", dicas: ["Técnico português", "Comandou o Botafogo", "Campanha histórica"] },
    { palavra: "RENATO GAUCHO", dicas: ["Técnico do Grêmio", "Ídolo", "Campeão"] },
    { palavra: "ROGER MACHADO", dicas: ["Técnico brasileiro", "Estrategista", "Ex-jogador"] },
    { palavra: "ABEL FERREIRA", dicas: ["Técnico do Palmeiras", "Português", "Campeão de várias Libertadores"] },
    { palavra: "CESAR SAMPAIO", dicas: ["Ex-jogador e auxiliar", "Volante histórico", "Destaque da Seleção"] },

    // ==========================================
    // 10. RECORDES E CURIOSIDADES (20)
    // ==========================================
    { palavra: "PENTA", dicas: ["5 títulos do Brasil", "Conquistado em 2002", "Ronaldo foi o artilheiro do torneio"] },
    { palavra: "TETRA", dicas: ["4 títulos do Brasil", "Conquistado em 1994", "Romário foi o craque do torneio"] },
    { palavra: "MARACANAZO", dicas: ["Brasil x Uruguai 1950", "Trágica derrota do Brasil em casa", "Jogo histórico"] },
    { palavra: "MINEIRAZO", dicas: ["Brasil 1 x 7 Alemanha", "Ocorrido em 2014", "Belo Horizonte"] },
    { palavra: "MAO DE DEUS", dicas: ["Gol de mão de Maradona", "Copa de 1986", "Contra a Inglaterra"] },
    { palavra: "HAT TRICK", dicas: ["Termo para quando um jogador faz 3 gols", "Leônidas fez um em 1938", "Expressão de origem inglesa"] },
    { palavra: "KLOSE", dicas: ["Maior artilheiro da história das Copas", "Alemão", "Marcou 16 gols no total"] },
    { palavra: "PENALTI", dicas: ["Tiro livre da marca de 11 metros", "Decisão na final de 1994", "Baggio isolou a bola"] },
    { palavra: "TRI", dicas: ["3 títulos do Brasil", "Conquistado em 1970", "Esquadrão liderado por Pelé"] },
    { palavra: "BOLA DE OURO", dicas: ["Prêmio da France Football", "Melhor jogador do mundo", "Messi tem 8"] },
    { palavra: "CHUTEIRA", dicas: ["Calçado específico para o gramado", "Possui travas na sola", "Modelos famosos da Nike, Adidas e Puma"] },
    { palavra: "UNIFORME", dicas: ["Conjunto de camisa, calção e meiões", "Identidade visual do time em campo", "Manto sagrado"] },
    { palavra: "BICICLETA", dicas: ["Chute acrobático no ar de costas para o gol", "Leônidas da Silva popularizou", "Plástica perfeita"] },
    { palavra: "FALTA", dicas: ["Infração cometida sobre o adversário", "Pode ser cobrança direta para o gol", "Barreira tenta bloquear"] },
    { palavra: "CARTAO", dicas: ["Item de advertência do árbitro", "Pode ser amarelo ou vermelho", "Exclui o jogador se for repetido"] },
    { palavra: "VAR", dicas: ["Árbitro de vídeo", "Tecnologia para revisar lances capitais", "Checa gols, cartões e impedimentos"] },
    { palavra: "GOL", dicas: ["Momento supremo do futebol", "Balançar a rede", "Ponto máximo da partida"] },
    { palavra: "BOLA", dicas: ["O objeto principal do esporte", "Formato esférico", "A Al Rihla e a Jabulani foram exemplos"] },
    { palavra: "IMPEDIMENTO", dicas: ["Regra do futebol", "Atacante adiantado", "Bandeira"] },
    { palavra: "ESCANTEIO", dicas: ["Cobrança de canto", "Lateral", "Gol de cabeça"] },

    // ==========================================
    // 11. CLUBES BRASILEIROS - FLAMENGO (20)
    // ==========================================
    { palavra: "FLAMENGO", dicas: ["Clube carioca fundado em 1895", "Rubro-Negro", "Maior torcida do Brasil"] },
    { palavra: "ZICO", dicas: ["Maior ídolo da história do Flamengo", "Galinho de Quintino", "Maior artilheiro do clube"] },
    { palavra: "JUNIOR", dicas: ["Lateral-esquerdo campeão mundial em 1981", "Capitão do time histórico", "Também atuou como meio-campista"] },
    { palavra: "ADILIO", dicas: ["Meia campeão mundial em 1981", "Cria da Gávea", "Camisa 8 do time histórico"] },
    { palavra: "NUNES", dicas: ["Centroavante campeão mundial em 1981", "Conhecido como João Danado", "Fez 2 gols na final contra o Liverpool"] },
    { palavra: "GABIGOL", dicas: ["Autor dos 2 gols da virada na final da Libertadores de 2019", "Um dos maiores artilheiros do Flamengo", "Ídolo da torcida"] },
    { palavra: "ARRASCAETA", dicas: ["Meia uruguaio", "Campeão da Libertadores pelo Flamengo", "Revelado pelo Defensor Sporting"] },
    { palavra: "BRUNO HENRIQUE", dicas: ["Atacante conhecido pela velocidade", "Campeão da Libertadores pelo Flamengo", "Revelado pelo Goiás"] },
    { palavra: "EVERTON RIBEIRO", dicas: ["Meia campeão da Libertadores pelo Flamengo", "Vestiu a camisa 7", "Revelado pelo Coritiba"] },
    { palavra: "GERSON", dicas: ["Volante revelado pelo Fluminense", "Conhecido como Coringa", "Capitão do Flamengo"] },
    { palavra: "DAVID LUIZ", dicas: ["Zagueiro campeão da Libertadores pelo Flamengo", "Revelado pelo Vitória", "Também defendeu Chelsea, PSG e Arsenal"] },
    { palavra: "PETKOVIC", dicas: ["Meia sérvio", "Autor do histórico gol de falta de 2001", "Ídolo do título brasileiro de 2009"] },
    { palavra: "ADRIANO", dicas: ["Conhecido como Imperador", "Artilheiro do Campeonato Brasileiro de 2009", "Revelado pelo Flamengo"] },
    { palavra: "1981", dicas: ["Ano do Mundial do Flamengo", "Vitória por 3 a 0 sobre o Liverpool no Japão", "Nunes marcou 2 gols na decisão"] },
    { palavra: "2019", dicas: ["Ano da Libertadores do Flamengo", "Virada por 2 a 1 sobre o River Plate", "Final disputada em Lima, no Peru"] },
    { palavra: "1980", dicas: ["Primeiro título brasileiro do Flamengo", "Zico foi o artilheiro", "Time histórico"] },
    { palavra: "1982", dicas: ["Bicampeão brasileiro", "Time de Zico", "Título sobre o Grêmio"] },
    { palavra: "1983", dicas: ["Tricampeão brasileiro", "Zico artilheiro", "Flamengo"] },
    { palavra: "1992", dicas: ["Campeão brasileiro", "Time de Júnior", "Flamengo"] },
    { palavra: "2009", dicas: ["Campeão brasileiro", "Petkovic herói", "Adriano artilheiro"] },

    // ==========================================
    // 12. CLUBES BRASILEIROS - CORINTHIANS (15)
    // ==========================================
    { palavra: "CORINTHIANS", dicas: ["Clube paulista fundado em 1910", "Conhecido como Timão", "Maior campeão paulista"] },
    { palavra: "CASSIO", dicas: ["Goleiro histórico do Corinthians", "Herói do Mundial de 2012", "Defendeu o chute de Diego Souza na Libertadores"] },
    { palavra: "RONALDO", dicas: ["Conhecido como Fenômeno", "Conquistou a Copa do Brasil de 2009", "Encerrou a carreira no Corinthians"] },
    { palavra: "MARCELINHO", dicas: ["Maior cobrador de faltas da história do Corinthians", "Conhecido como Pé de Anjo", "Ídolo dos títulos dos anos 90"] },
    { palavra: "SOCRATES", dicas: ["Líder da Democracia Corinthiana", "Médico formado", "Um dos maiores ídolos da história do clube"] },
    { palavra: "RIVELINO", dicas: ["Revelado pelo Corinthians", "Conhecido como Reizinho do Parque", "Craque da Copa de 1970"] },
    { palavra: "VAMPETA", dicas: ["Volante campeão mundial em 2000", "Campeão brasileiro pelo Corinthians", "Fez parte de uma das gerações mais vitoriosas do clube"] },
    { palavra: "YURI ALBERTO", dicas: ["Centroavante", "Revelado pelo Santos", "Atacante do Corinthians"] },
    { palavra: "GARRO", dicas: ["Meia argentino", "Especialista em assistências", "Camisa 10 do Corinthians"] },
    { palavra: "ROGER GUEDES", dicas: ["Atacante que se destacou pelo Corinthians", "Revelado pelo Criciúma", "Foi um dos artilheiros da equipe"] },
    { palavra: "PAULINHO", dicas: ["Volante campeão da Libertadores e do Mundial de 2012", "Revelado pelo Pão de Açúcar", "Ídolo da torcida"] },
    { palavra: "EDILSON", dicas: ["Atacante conhecido como Capetinha", "Campeão mundial em 2000", "Ídolo do Corinthians"] },
    { palavra: "2000", dicas: ["Ano do primeiro Mundial do Corinthians", "Título conquistado sobre o Vasco nos pênaltis", "Disputado no Brasil"] },
    { palavra: "2012", dicas: ["Ano do segundo Mundial do Corinthians", "Vitória por 1 a 0 sobre o Chelsea", "Guerrero marcou o gol do título"] },
    { palavra: "1998", dicas: ["Ano do segundo Campeonato Brasileiro do Corinthians", "Marcelinho Carioca foi um dos destaques", "Vampeta e Rincón eram titulares"] },
    
    // ==========================================
    // 13. CLUBES BRASILEIROS - PALMEIRAS (15)
    // ==========================================
    { palavra: "PALMEIRAS", dicas: ["Clube paulista fundado em 1914", "Conhecido como Verdão", "Maior campeão brasileiro"] },
    { palavra: "ADEMIR DA GUIA", dicas: ["Maior ídolo da história do Palmeiras", "Conhecido como Divino", "Um dos maiores meias do futebol brasileiro"] },
    { palavra: "DUDU", dicas: ["Um dos maiores ídolos recentes do Palmeiras", "Atacante campeão da Libertadores", "Vestiu a camisa 7 por muitos anos"] },
    { palavra: "GUSTAVO SCARPA", dicas: ["Meia campeão da Libertadores pelo Palmeiras", "Eleito o melhor jogador do Brasileirão de 2022", "Revelado pelo Fluminense"] },
    { palavra: "RAPHAEL VEIGA", dicas: ["Meia do Palmeiras", "Especialista em cobranças de pênalti", "Destaque nas Libertadores de 2020 e 2021"] },
    { palavra: "RONY", dicas: ["Atacante do Palmeiras", "Destaque nas campanhas da Libertadores", "Conhecido pelas bicicletas"] },
    { palavra: "MARCOS", dicas: ["Goleiro campeão da Libertadores de 1999", "Conhecido como São Marcos", "Ídolo da torcida palmeirense"] },
    { palavra: "ZE ROBERTO", dicas: ["Volante e lateral-esquerdo", "Jogou no Palmeiras já veterano", "Destacou-se pela excelente condição física"] },
    { palavra: "EDMUNDO", dicas: ["Conhecido como Animal", "Ídolo do Palmeiras nos anos 90", "Campeão brasileiro de 1993 e 1994"] },
    { palavra: "EVAIR", dicas: ["Centroavante histórico do Palmeiras", "Artilheiro na década de 90", "Ídolo palmeirense"] },
    { palavra: "1999", dicas: ["Ano da primeira Libertadores do Palmeiras", "Título conquistado sobre o Deportivo Cali", "Marcos defendeu pênalti decisivo"] },
    { palavra: "2020", dicas: ["Ano da segunda Libertadores do Palmeiras", "Vitória sobre o Santos por 1 a 0", "Breno Lopes marcou o gol do título"] },
    { palavra: "2021", dicas: ["Ano da terceira Libertadores do Palmeiras", "Vitória sobre o Flamengo na prorrogação", "Deyverson marcou o gol do título"] },
    { palavra: "2022", dicas: ["Ano do 11º Campeonato Brasileiro do Palmeiras", "Time comandado por Abel Ferreira", "Gustavo Scarpa foi um dos destaques"] },
    { palavra: "2018", dicas: ["Ano do Campeonato Brasileiro do Palmeiras", "Time comandado por Felipão", "Dudu foi um dos principais destaques"] },

    // ==========================================
    // 14. CLUBES BRASILEIROS - SANTOS (15)
    // ==========================================
    { palavra: "SANTOS", dicas: ["Clube paulista fundado em 1912", "Conhecido como Peixe", "Clube onde Pelé fez história"] },
    { palavra: "PELE", dicas: ["Maior jogador da história do Santos", "Rei do Futebol", "Bicampeão mundial pelo clube"] },
    { palavra: "GILMAR", dicas: ["Goleiro histórico do Santos", "Campeão mundial pelo clube", "Também foi campeão do mundo pela Seleção"] },
    { palavra: "PEPE", dicas: ["Maior artilheiro do Santos depois de Pelé", "Conhecido como Canhão da Vila", "Bicampeão mundial pelo clube"] },
    { palavra: "MENGALVIO", dicas: ["Meia do histórico ataque santista", "Campeão mundial pelo Santos", "Fez parte do time de Pelé"] },
    { palavra: "ZITO", dicas: ["Volante histórico do Santos", "Conhecido como Gerente", "Bicampeão mundial pelo clube"] },
    { palavra: "ORLANDO", dicas: ["Zagueiro histórico do Santos", "Capitão do time de Pelé", "Bicampeão mundial pelo clube"] },
    { palavra: "CLODOALDO", dicas: ["Volante histórico do Santos", "Campeão do mundo com o Brasil em 1970", "Grande marcador"] },
    { palavra: "NEYMAR", dicas: ["Revelado pelo Santos", "Campeão da Libertadores de 2011", "Maior ídolo recente do clube"] },
    { palavra: "ROBINHO", dicas: ["Revelado pelo Santos", "Campeão brasileiro de 2002", "Conhecido pelas pedaladas"] },
    { palavra: "GANSO", dicas: ["Meia revelado na base do Santos", "Campeão da Libertadores de 2011", "Formou dupla com Neymar"] },
    { palavra: "1962", dicas: ["Ano do primeiro Mundial do Santos", "Título conquistado sobre o Benfica", "Pelé brilhou na decisão"] },
    { palavra: "1963", dicas: ["Ano do segundo Mundial do Santos", "Título conquistado sobre o Milan", "O Santos venceu a decisão em três partidas"] },
    { palavra: "2002", dicas: ["Ano do Campeonato Brasileiro do Santos", "Time comandado por Emerson Leão", "Robinho e Diego eram os principais destaques"] },
    { palavra: "2011", dicas: ["Ano da terceira Libertadores do Santos", "Vitória sobre o Peñarol", "Neymar foi o principal destaque da campanha"] },
    
    // ==========================================
    // 15. CLUBES BRASILEIROS - SÃO PAULO (15)
    // ==========================================
    { palavra: "SAO PAULO", dicas: ["Clube paulista fundado in 1930", "Conhecido como Tricolor Paulista", "Único brasileiro tricampeão mundial"] },
    { palavra: "ROGERIO CENI", dicas: ["Maior ídolo da história do São Paulo", "Goleiro-artilheiro", "Maior goleador entre os goleiros"] },
    { palavra: "RAI", dicas: ["Meia e camisa 10 histórico", "Capitão dos Mundiais de 1992 e 1993", "Ídolo do São Paulo"] },
    { palavra: "MULLER", dicas: ["Atacante revelado pelo São Paulo", "Campeão mundial em 1992 e 1993", "Fez dupla histórica com Raí"] },
    { palavra: "CARECA", dicas: ["Centroavante campeão brasileiro de 1986", "Revelado pelo Guarani", "Um dos maiores atacantes da história do São Paulo"] },
    { palavra: "TELE", dicas: ["Treinador histórico do São Paulo", "Comandou os títulos mundiais de 1992 e 1993", "Conhecido pela disciplina e pelo futebol ofensivo"] },
    { palavra: "SERGINHO", dicas: ["Centroavante histórico do São Paulo", "Conhecido como Serginho Chulapa", "Maior artilheiro da história do clube"] },
    { palavra: "PALHINHA", dicas: ["Atacante campeão mundial nos anos 90", "Ídolo da torcida são-paulina", "Conhecido pelos gols decisivos"] },
    { palavra: "LUCAS", dicas: ["Revelado pelo São Paulo", "Campeão da Copa Sul-Americana de 2012", "Conhecido pela velocidade"] },
    { palavra: "OSCAR", dicas: ["Meia revelado na base do São Paulo", "Atuou na Seleção Brasileira", "Polêmica transferência para o Internacional"] },
    { palavra: "CASEMIRO", dicas: ["Volante revelado pelo São Paulo", "Construiu carreira de sucesso na Europa", "Campeão de várias Champions League"] },
    { palavra: "1992", dicas: ["Ano do primeiro Mundial do São Paulo", "Vitória por 2 a 1 sobre o Barcelona", "Final disputada em Tóquio"] },
    { palavra: "1993", dicas: ["Ano do bicampeonato mundial do São Paulo", "Vitória por 3 a 2 sobre o Milan", "Final disputada em Tóquio"] },
    { palavra: "2005", dicas: ["Ano da terceira Libertadores do São Paulo", "Vitória sobre o Athletico Paranaense", "Rogério Ceni era o capitão"] },
    { palavra: "2006", dicas: ["Ano do Campeonato Brasileiro", "Primeiro de três títulos consecutivos", "Muricy Ramalho era o treinador"] },

    // ==========================================
    // 16. CLUBES BRASILEIROS - FLUMINENSE (15)
    // ==========================================
    { palavra: "FLUMINENSE", dicas: ["Clube carioca fundado em 1902", "Conhecido como Tricolor das Laranjeiras", "Campeão da Libertadores de 2023"] },
    { palavra: "FRED", dicas: ["Maior ídolo da história recente do Fluminense", "Maior artilheiro do clube no século XXI", "Centroavante"] },
    { palavra: "CONCA", dicas: ["Meia argentino", "Craque do Brasileirão de 2010", "Ídolo da torcida tricolor"] },
    { palavra: "THIAGO NEVES", dicas: ["Meia habilidoso", "Campeão brasileiro de 2012", "Marcou 3 gols na final da Libertadores de 2008"] },
    { palavra: "GUM", dicas: ["Zagueiro capitão", "Campeão brasileiro de 2010 e 2012", "Ídolo da torcida"] },
    { palavra: "DIGUINHO", dicas: ["Volante marcador", "Campeão brasileiro de 2010 e 2012", "Querido pela torcida"] },
    { palavra: "WASHINGTON", dicas: ["Conhecido como Coração Valente", "Artilheiro do Fluminense", "Vice-campeão da Libertadores de 2008"] },
    { palavra: "CANO", dicas: ["Centroavante argentino", "Artilheiro da Libertadores de 2023", "Ídolo da conquista continental"] },
    { palavra: "ARIAS", dicas: ["Atacante colombiano", "Destaque da Libertadores de 2023", "Conhecido pelos dribles"] },
    { palavra: "NINO", dicas: ["Zagueiro capitão do título da Libertadores", "Revelado pelo Criciúma", "Zagueiro clássico"] },
    { palavra: "FABIO", dicas: ["Goleiro campeão da Libertadores de 2023", "Ídolo histórico nacional", "Um dos jogadores com mais partidas na história do futebol brasileiro"] },
    { palavra: "GANSO", dicas: ["Meia com estilo clássico", "Campeão da Libertadores de 2023", "Conhecido pela visão de jogo"] },
    { palavra: "2010", dicas: ["Ano do terceiro Campeonato Brasileiro do Fluminense", "Conca foi eleito o craque da competição", "Muricy Ramalho era o técnico"] },
    { palavra: "2012", dicas: ["Ano do tetracampeonato brasileiro", "Fred foi o artilheiro do campeonato", "Abel Braga era o treinador"] },
    { palavra: "2023", dicas: ["Ano da primeira Libertadores do Fluminense", "Vitória sobre o Boca Juniors", "John Kennedy marcou o gol decisivo da prorrogação"] },

    // ==========================================
    // 17. CLUBES BRASILEIROS - BOTAFOGO (15)
    // ==========================================
    { palavra: "BOTAFOGO", dicas: ["Clube carioca fundado em 1904", "Conhecido como Fogão", "Clube de Garrincha e Nilton Santos"] },
    { palavra: "GARRINCHA", dicas: ["Maior ídolo da história do Botafogo", "Anjo das Pernas Tortas", "Bicampeão mundial pela Seleção"] },
    { palavra: "NILTON SANTOS", dicas: ["Conhecido como Enciclopédia do Futebol", "Lateral-esquerdo histórico", "Bicampeão mundial pela Seleção"] },
    { palavra: "DIDI", dicas: ["Inventou a folha seca", "Craque da Copa de 1958", "Ídolo do Botafogo"] },
    { palavra: "ZAGALLO", dicas: ["Ponta-esquerda do Botafogo", "Único tetracampeão mundial", "Bicampeão como jogador"] },
    { palavra: "AMARILDO", dicas: ["Substituiu Pelé na Copa de 1962", "Atacante histórico do Botafogo", "Campeão do mundo"] },
    { palavra: "TIQUINHO", dicas: ["Centroavante", "Destaque do Botafogo na década de 2020", "Conhecido pelo faro de gol"] },
    { palavra: "1995", dicas: ["Ano do Campeonato Brasileiro do Botafogo", "Túlio Maravilha foi o artilheiro", "Vitória sobre o Santos na final"] },
    { palavra: "2024", dicas: ["Ano da primeira Libertadores do Botafogo", "Também conquistou o Campeonato Brasileiro", "Venceu o Atlético-MG na final continental"] },
    { palavra: "TULIO", dicas: ["Conhecido como Túlio Maravilha", "Artilheiro do título brasileiro de 1995", "Um dos maiores goleadores da história do Botafogo"] },
    { palavra: "1993", dicas: ["Ano da conquista da Copa Conmebol", "Primeiro título internacional oficial do Botafogo", "Vitória sobre o Peñarol"] },
    { palavra: "1968", dicas: ["Ano da conquista da Taça Brasil", "Botafogo tinha Gérson, Jairzinho e Paulo César", "Um dos grandes times da história do clube"] },
    { palavra: "JAIRZINHO", dicas: ["Conhecido como Furacão da Copa", "Ídolo do Botafogo", "Marcou gols em todos os jogos da Copa de 1970"] },
    { palavra: "NILTON", dicas: ["Primeiro nome de batismo do lendário Enciclopédia", "Ídolo eterno do Botafogo", "Dá nome ao estádio do clube"] },
    { palavra: "2025", dicas: ["Ano da conquista da Recopa Sul-Americana", "Título internacional do Botafogo", "Disputada contra o Racing"] },
    
    // ==========================================
    // 18. CLUBES BRASILEIROS - VASCO (15)
    // ==========================================
    { palavra: "VASCO", dicas: ["Clube carioca fundado em 1898", "Gigante da Colina", "Resposta histórica contra o racismo e o elitismo"] },
    { palavra: "DINAMITE", dicas: ["Maior ídolo da história do Vasco", "Atacante", "Maior artilheiro da história do Brasileirão"] },
    { palavra: "ROMARIO", dicas: ["Atacante ídolo do Vasco", "Camisa 11", "Revelado na base do Vasco"] },
    { palavra: "EDMUNDO", dicas: ["Atacante ídolo dos anos 90", "Animal", "Campeão brasileiro de 1997 com grande destaque"] },
    { palavra: "PEDRINHO", dicas: ["Meia ídolo dos anos 90", "Cria da base do clube", "Campeão brasileiro de 1997"] },
    { palavra: "FELIPE", dicas: ["Lateral e meia clássico dos anos 90", "Multicampeão", "Campeão brasileiro de 1997"] },
    { palavra: "DONIZETE", dicas: ["Atacante do Vasco nos anos 90", "Conhecido como Pantera", "Destaque no título da Libertadores de 1998"] },
    { palavra: "MAURO GALVAO", dicas: ["Zagueiro ídolo dos anos 90", "Capitão", "Campeão da Libertadores de 1998"] },
    { palavra: "VALDIR", dicas: ["Atacante conhecido como Valdir Bigode", "Goleador", "Destaque no Vasco nos anos 90"] },
    { palavra: "VEGETTI", dicas: ["Atacante atual do Vasco", "Pirata", "Artilheiro do clube"] },
    { palavra: "1974", dicas: ["Ano do Brasileiro do Vasco", "Destaque com Roberto Dinamite", "Primeiro título brasileiro do clube"] },
    { palavra: "1989", dicas: ["Ano do Brasileiro do Vasco", "Time campeão com gol de Sorato na final", "Título nacional"] },
    { palavra: "1997", dicas: ["Ano do Brasileiro do Vasco", "Grande campanha com Edmundo", "Campeão brasileiro"] },
    { palavra: "2000", dicas: ["Ano do Brasileiro do Vasco", "Romário em grande fase", "Campeão da Copa João Havelange"] },
    { palavra: "1998", dicas: ["Ano da Libertadores do Vasco", "Venceu o Barcelona SC na final no ano do centenário", "Título continental"] },

    // ==========================================
    // 19. CLUBES BRASILEIROS - CRUZEIRO (15)
    // ==========================================
    { palavra: "CRUZEIRO", dicas: ["Clube mineiro fundado em 1921", "Conhecido como Raposa", "Hexacampeão da Copa do Brasil"] },
    { palavra: "TOSTAO", dicas: ["Maior ídolo do Cruzeiro", "Campeão do mundo 1970", "Meia genial"] },
    { palavra: "DIRCEU LOPES", dicas: ["Meia histórico", "Um dos maiores craques do Cruzeiro", "Campeão da Taça Brasil de 1966"] },
    { palavra: "RAUL", dicas: ["Goleiro histórico que jogava de camisa amarela", "Campeão da Libertadores de 1976", "Ídolo do Cruzeiro"] },
    { palavra: "PALINHA", dicas: ["Atacante artilheiro", "Campeão da Libertadores de 1976", "Goleador do time"] },
    { palavra: "NELINHO", dicas: ["Lateral direito famoso pelo chute de trivela", "Ídolo da torcida", "Grande batedor de faltas"] },
    { palavra: "PIAZZA", dicas: ["Volante e zagueiro", "Capitão na Libertadores de 1976", "Campeão mundial de 1970"] },
    { palavra: "ALEX", dicas: ["Meia da Tríplice Coroa em 2003", "Um dos maiores ídolos do Cruzeiro", "Passagem pelo Fenerbahçe"] },
    { palavra: "MARCELO MORENO", dicas: ["Atacante boliviano", "Artilheiro do Cruzeiro", "Ídolo da torcida"] },
    { palavra: "ARRASCAETA", dicas: ["Meia uruguaio", "Bicampeão da Copa do Brasil pelo Cruzeiro", "Destaque técnico"] },
    { palavra: "FABIO", dicas: ["Goleiro histórico do Cruzeiro", "Jogador com mais partidas na história do clube", "Campeão da Copa do Brasil"] },
    { palavra: "DEDE", dicas: ["Zagueiro", "Conhecido como Mito", "Bicampeão brasileiro pelo clube"] },
    { palavra: "THIAGO NEVES", dicas: ["Meia", "Protagonista nos títulos da Copa do Brasil de 17 e 18", "Habilidoso"] },
    { palavra: "1976", dicas: ["Ano da primeira Libertadores do Cruzeiro", "Vitória sobre o River Plate", "Título inédito"] },
    { palavra: "1997", dicas: ["Ano do bicampeonato da Libertadores", "Gol de Elivélton na final", "Cruzeiro campeão"] },

    // ==========================================
    // 20. CLUBES BRASILEIROS - ATLÉTICO MINEIRO (15)
    // ==========================================
    { palavra: "ATLETICO MINEIRO", dicas: ["Clube mineiro fundado em 1908", "Conhecido como Galo", "Campeão da Libertadores de 2013"] },
    { palavra: "REINALDO", dicas: ["Maior ídolo do Atlético Mineiro", "Atacante genial", "Famoso pela comemoração do punho cerrado"] },
    { palavra: "RONALDINHO", dicas: ["Bruxo", "Líder técnico do Atlético Mineiro", "Campeão da Libertadores de 2013"] },
    { palavra: "VICTOR", dicas: ["Goleiro conhecido como São Victor", "Defendeu pênalti histórico contra o Tijuana", "Milagreiro de 2013"] },
    { palavra: "LEONARDO SILVA", dicas: ["Zagueiro artilheiro e ídolo", "Fez o gol que levou a final de 2013 para a prorrogação", "Capitão"] },
    { palavra: "PIERRE", dicas: ["Volante de muita raça", "Campeão da Libertadores de 2013", "Ídolo da massa atleticana"] },
    { palavra: "REVER", dicas: ["Zagueiro multicampeão", "Capitão que ergueu a taça em 2013", "Histórico no clube"] },
    { palavra: "BERNARD", dicas: ["Atacante rápido", "Cria do Atlético com 'alegria nas pernas'", "Campeão da Libertadores de 2013"] },
    { palavra: "TARDELLI", dicas: ["Atacante decisivo", "Artilheiro em clássicos", "Campeão da Libertadores de 2013"] },
    { palavra: "GILBERTO SILVA", dicas: ["Volante campeão do mundo em 2002", "Revelado pelo América, teve grande fase no Galo", "Campeão em 2013"] },
    { palavra: "HULK", dicas: ["Atacante de muita força física", "Líder dos títulos do Brasileirão e Copa do Brasil de 2021", "Grande artilheiro atual"] },
    { palavra: "ZARACHO", dicas: ["Meia argentino", "Muito dinâmico", "Destaque nas conquistas recentes"] },
    { palavra: "1971", dicas: ["Ano do primeiro Campeonato Brasileiro do Atlético", "Time comandado por Telê Santana", "Campeão nacional"] },
    { palavra: "2013", dicas: ["Ano da primeira Libertadores do Atlético", "Vitória emocionante sobre o Olimpia nos pênaltis", "Título inédito"] },
    { palavra: "2021", dicas: ["Ano do bicampeonato do Campeonato Brasileiro do Atlético", "Hulk artilheiro", "Cuca treinador"] },

    // ==========================================
    // 21. CLUBES BRASILEIROS - GRÊMIO (15)
    // ==========================================
    { palavra: "GREMIO", dicas: ["Clube gaúcho fundado em 1903", "Conhecido como Tricolor Gaúcho", "Tricampeão da Libertadores"] },
    { palavra: "RENATO GAUCHO", dicas: ["Maior ídolo do Grêmio", "Atacante no Mundial e técnico na Libertadores", "Campeão do Mundo em 1983"] },
    { palavra: "GEROMEL", dicas: ["Zagueiro histórico moderno", "Ídolo da conquista da Libertadores de 2017", "Parceria lendária com Kannemann"] },
    { palavra: "PAULO NUNES", dicas: ["Atacante irreverente", "Conhecido pelas comemorações com máscaras", "Campeão da Libertadores de 1995"] },
    { palavra: "DINHO", dicas: ["Volante xerife de muita pegada", "Símbolo da raça gremista", "Campeão da Libertadores de 1995"] },
    { palavra: "DANRLEI", dicas: ["Goleiro multicampeão e muito copeiro", "Ídolo da década de 90", "Campeão da Libertadores de 1995"] },
    { palavra: "ARCE", dicas: ["Lateral direito paraguaio", "Especialista em faltas e cruzamentos", "Campeão da Libertadores de 1995"] },
    { palavra: "LUCAS LEIVA", dicas: ["Volante formado na base", "Destaque na Batalha dos Aflitos", "Grande passagem pelo Liverpool"] },
    { palavra: "ARTHUR", dicas: ["Meia de excelente passe", "Melhor em campo na final da Libertadores de 2017", "Vendido ao Barcelona"] },
    { palavra: "PEPE", dicas: ["Atacante rápido", "Revelado pelo Grêmio", "Negociado com o Porto"] },
    { palavra: "LUAN", dicas: ["Rei da América em 2017", "Principal jogador na conquista do Tri", "Meia-atacante talentoso"] },
    { palavra: "MAICON", dicas: ["Volante capitão e líder do meio-campo", "Destaque na conquista da Copa do Brasil de 2016", "Qualidade técnica no passe"] },
    { palavra: "1983", dicas: ["Ano do Mundial de Clubes do Grêmio", "Vitória sobre o Hamburgo por 2 a 1", "Renato Gaúcho marcou os dois gols"] },
    { palavra: "1995", dicas: ["Ano do bicampeonato da Libertadores", "Time comandado por Luiz Felipe Scolari", "Vitória sobre o Atlético Nacional"] },
    { palavra: "2017", dicas: ["Ano da terceira Libertadores do Grêmio", "Vitória sobre o Lanús na Argentina", "Comandado por Renato Portaluppi"] },

    // ==========================================
    // 22. CLUBES BRASILEIROS - INTERNACIONAL (15)
    // ==========================================
    { palavra: "INTERNACIONAL", dicas: ["Clube gaúcho fundado em 1909", "Conhecido como Colorado", "Bicampeão da Libertadores"] },
    { palavra: "FALCAO", dicas: ["Maior ídolo do Inter", "Rei de Roma", "Meia elegante e técnico"] },
    { palavra: "FERNANDAO", dicas: ["Atacante eterno capitão", "Ergueu a Libertadores e o Mundial de 2006", "Líder e ídolo supremo"] },
    { palavra: "INDIO", dicas: ["Zagueiro multicampeão", "Zagueiro artilheiro em clássicos Grenal", "Campeão da Libertadores de 2006"] },
    { palavra: "CLEMER", dicas: ["Goleiro experiente", "Paredão do time campeão mundial", "Campeão da Libertadores de 2006"] },
    { palavra: "DALESSANDRO", dicas: ["Meia argentino e camisa 10", "Criador do drible 'La Boba'", "Campeão da Libertadores de 2010"] },
    { palavra: "SOBIS", dicas: ["Atacante herói", "Marcou dois gols na final da Libertadores de 2006 contra o São Paulo", "Revelado no clube"] },
    { palavra: "ALEXANDRE PATO", dicas: ["Atacante velocista", "Estreou brilhando no Mundial com apenas 17 anos", "Vendido ao Milan"] },
    { palavra: "LUIZ ADRIANO", dicas: ["Atacante", "Fez gol decisivo na semifinal do Mundial de 2006", "Longa passagem pelo Shakhtar"] },
    { palavra: "DAMIAO", dicas: ["Centroavante das bicicletas e lambretas", "Marcou gol na final da Libertadores de 2010", "Destaque colorado"] },
    { palavra: "VALDIVIA", dicas: ["Meia-atacante cabeludo", "Destaque na campanha da Libertadores de 2015", "Apelido irreverente"] },
    { palavra: "TAFFAREL", dicas: ["Goleiro revelado no Colorado", "Um dos maiores da história do futebol brasileiro", "Campeão do mundo em 1994"] },
    { palavra: "2006", dicas: ["Ano da primeira Libertadores e do Mundial do Inter", "Vitória histórica sobre o Barcelona de Ronaldinho Gaúcho", "Glória máxima"] },
    { palavra: "1979", dicas: ["Ano do tricampeonato brasileiro do Inter", "Campeão invicto", "Falcão liderava o esquadrão"] },
    { palavra: "1976", dicas: ["Ano do segundo Brasileiro do Inter", "Bicampeonato com gol de Figueroa", "Falcão capitão"] },

    // ==========================================
    // 23. CLUBES BRASILEIROS - OUTROS (15)
    // ==========================================
    { palavra: "BAHIA", dicas: ["Clube baiano fundado em 1931", "Conhecido como Tricolor de Aço", "Campeão brasileiro de 1959 e 1988"] },
    { palavra: "VITORIA", dicas: ["Clube baiano fundado em 1899", "Conhecido como Leão da Barra", "Tradicional clube formador"] },
    { palavra: "SPORT", dicas: ["Clube pernambucano fundado em 1905", "Conhecido como Leão da Ilha", "Campeão brasileiro de 1987 e da Copa do Brasil de 2008"] },
    { palavra: "NAUTICO", dicas: ["Clube pernambucano fundado em 1901", "Conhecido como Timbu", "Hexacampeão estadual na década de 60"] },
    { palavra: "SANTA CRUZ", dicas: ["Clube pernambucano fundado em 1914", "Conhecido como Cobra Coral", "Famoso pelas grandes multidões no Arruda"] },
    { palavra: "CEARA", dicas: ["Clube cearense fundado em 1914", "Conhecido como Vozão", "Bicampeão invicto da Copa do Nordeste"] },
    { palavra: "FORTALEZA", dicas: ["Clube cearense fundado em 1918", "Conhecido como Leão do Pici", "Destaque recente em competições internacionais"] },
    { palavra: "GOIAS", dicas: ["Clube goiano fundado em 1943", "Conhecido como Esmeraldino", "Maior campeão do seu estado"] },
    { palavra: "ATLETICO GO", dicas: ["Clube goiano fundado em 1937", "Conhecido como Dragão", "Tradicional clube da capital goiana"] },
    { palavra: "VILA NOVA", dicas: ["Clube goiano fundado em 1943", "Conhecido como Tigre", "Famoso por sua torcida apaixonada"] },
    { palavra: "CUIABA", dicas: ["Clube mato-grossense fundado em 2001", "Conhecido como Dourado", "Representante do Centro-Oeste na elite recente"] },
    { palavra: "BRASILIENSE", dicas: ["Clube do Distrito Federal", "Conhecido como Jacaré", "Vice-campeão da Copa do Brasil de 2002"] },
    { palavra: "REMO", dicas: ["Clube paraense fundado em 1905", "Conhecido como Leão Azul", "Faz com o Paysandu o maior clássico da Amazônia"] },
    { palavra: "PAYSANDU", dicas: ["Clube paraense fundado em 1914", "Conhecido como Papão da Curuzu", "Campeão da Copa dos Campeões de 2002"] },
    { palavra: "SAMPAIO CORREA", dicas: ["Clube maranhense fundado em 1923", "Conhecido como Bolívia Querida", "Campeão de três divisões nacionais diferentes"] },

    // ==========================================
    // 24. CLUBES INTERNACIONAIS (50)
    // ==========================================
    { palavra: "REAL MADRID", dicas: ["Clube espanhol", "15 títulos de Champions League", "Time de Mbappé e Vini Jr"] },
    { palavra: "BARCELONA", dicas: ["Clube espanhol", "5 Champions", "Histórico time de Lionel Messi"] },
    { palavra: "MANCHESTER CITY", dicas: ["Clube inglês", "Campeão mundial recente sob comando de Guardiola", "Time de Haaland"] },
    { palavra: "BAYERN", dicas: ["Clube alemão", "6 Champions", "Maior potência do futebol alemão"] },
    { palavra: "MILAN", dicas: ["Clube italiano", "7 Champions", "Segunda equipe com mais títulos continentais na Europa"] },
    { palavra: "LIVERPOOL", dicas: ["Clube inglês", "6 Champions", "Estádio lendário de Anfield Road"] },
    { palavra: "PSG", dicas: ["Clube francês", "Dominante nacionalmente na última década", "Time de Paris"] },
    { palavra: "JUVENTUS", dicas: ["Clube italiano", "Conhecida como a Velha Senhora", "Sediada em Turim"] },
    { palavra: "INTER", dicas: ["Clube italiano", "Time de Milão que veste azul e preto", "Internazionale"] },
    { palavra: "CHELSEA", dicas: ["Clube inglês", "2 Champions", "Time dos Blues de Londres"] },
    { palavra: "ARSENAL", dicas: ["Clube inglês", "Conhecidos como os Gunners", "Campeão invicto da Premier League em 2004"] },
    { palavra: "MANCHESTER UNITED", dicas: ["Clube inglês", "3 Champions", "Os Diabos Vermelhos de Old Trafford"] },
    { palavra: "ATLETICO MADRID", dicas: ["Clube espanhol", "Dirigido por longos anos por Diego Simeone", "Colchoneros"] },
    { palavra: "DORTMUND", dicas: ["Clube alemão", "Famoso pela Muralha Amarela", "Borussia"] },
    { palavra: "AJAX", dicas: ["Clube holandês", "4 Champions", "Revolucionou o futebol com Johan Cruyff"] },
    { palavra: "PSV", dicas: ["Clube holandês", "1 Champions", "Clube onde Romário e Ronaldo brilharam na Europa"] },
    { palavra: "BENFICA", dicas: ["Clube português", "2 Champions", "As Águias de Lisboa eternizadas por Eusébio"] },
    { palavra: "PORTO", dicas: ["Clube português", "2 Champions", "Os Dragões do Norte de Portugal"] },
    { palavra: "NAPOLI", dicas: ["Clube italiano", "Mando de campo no Estádio Diego Armando Maradona", "Sul da Itália"] },
    { palavra: "ROMA", dicas: ["Clube italiano", "Eternizado pelo capitão Francesco Totti", "Cidade eterna"] },
    { palavra: "LAZIO", dicas: ["Clube italiano", "Rival histórico da Roma", "Cores azul celeste e branco"] },
    { palavra: "FIORENTINA", dicas: ["Clube italiano", "A equipe Viola de Florença", "Ídolos como Batistuta"] },
    { palavra: "SAMPDORIA", dicas: ["Clube italiano", "Cidade de Gênova", "Bela camisa com listras horizontais"] },
    { palavra: "TORINO", dicas: ["Clube italiano", "Rival local da Juventus", "Histórico esquadrão dos anos 40"] },
    { palavra: "ATALANTA", dicas: ["Clube italiano", "Sediado em Bergamo", "Grande destaque tático europeu recente"] },
    { palavra: "BOLOGNA", dicas: ["Clube italiano", "Um dos clubes mais antigos e tradicionais da Itália", "Rossoblù"] },
    { palavra: "VERONA", dicas: ["Clube italiano", "Campeão surpreendente da Serie A em 1985", "Cidade de Romeu e Julieta"] },
    { palavra: "PALERMO", dicas: ["Clube italiano", "Famoso pelo seu uniforme inteiramente rosa", "Ilha da Sicília"] },
    { palavra: "CAGLIARI", dicas: ["Clube italiano", "Principal clube da ilha da Sardenha", "Campeão em 1970 com Gigi Riva"] },
    { palavra: "UDINESE", dicas: ["Clube italiano", "Clube onde Zico jogou na Itália", "Região de Friuli"] },
    { palavra: "SEVILLA", dicas: ["Clube espanhol", "Maior campeão da história da Europa League", "Andaluzia"] },
    { palavra: "VALENCIA", dicas: ["Clube espanhol", "Tradicional força que joga no Estádio de Mestalla", "Cores preta e branca"] },
    { palavra: "VILLARREAL", dicas: ["Clube espanhol", "Conhecido como o Submarino Amarelo", "Pequena cidade espanhola"] },
    { palavra: "BETIS", dicas: ["Clube espanhol", "Rival local do Sevilla", "Torcida fanática de verde e branco"] },
    { palavra: "SOCIEDAD", dicas: ["Clube espanhol", "Sediado em San Sebastián no País Basco", "Real Sociedad"] },
    { palavra: "LEVERKUSEN", dicas: ["Clube alemão", "Quebrou tabus com título invicto sob comando de Xabi Alonso", "Bayer"] },
    { palavra: "SCHALKE", dicas: ["Clube alemão", "Tradicional clube da região do Ruhr", "Famoso azul real"] },
    { palavra: "WOLFSBURG", dicas: ["Clube alemão", "Campeão da Bundesliga com Grafite e Dzeko", "Cidade da Volkswagen"] },
    { palavra: "BRIGHTON", dicas: ["Clube inglês", "Conhecido por excelente garimpo de jovens talentos", "Gulls"] },
    { palavra: "WEST HAM", dicas: ["Clube inglês", "Os Hammers do leste de Londres", "Famoso hino das bolhas de sabão"] },
    { palavra: "EVERTON", dicas: ["Clube inglês", "Rival municipal do Liverpool", "Joga tradicionalmente no Goodison Park"] },
    { palavra: "NEWCASTLE", dicas: ["Clube inglês", "Os Magpies que usam listras pretas e brancas", "Grande poder financeiro recente"] },
    { palavra: "ASTON VILLA", dicas: ["Clube inglês", "Campeão europeu em 1982", "Cidade de Birmingham"] },
    { palavra: "TOTTENHAM", dicas: ["Clube inglês", "Os Spurs de Londres", "Dono de um dos estádios mais modernos do mundo"] },
    { palavra: "LEICESTER", dicas: ["Clube inglês", "Campeão histórico e inacreditável da Premier League em 2016", "Foxes"] },
    { palavra: "WOLVERHAMPTON", dicas: ["Clube inglês", "Conhecido como Wolves", "Grande colônia de jogadores portugueses recentemente"] },
    { palavra: "FULHAM", dicas: ["Clube inglês", "Clube mais antigo de Londres na liga profissional", "Estádio de Craven Cottage"] },
    { palavra: "CRYSTAL PALACE", dicas: ["Clube inglês", "Localizado no sul de Londres", "Eagles"] },
    { palavra: "BRENTFORD", dicas: ["Clube inglês", "Conhecido como o time das abelhas", "Gestão baseada em estatísticas avançadas"] },
    { palavra: "NOTTINGHAM", dicas: ["Clube inglês", "Bicampeão consecutivo da Champions League sob comando de Brian Clough", "Forest"] },

    // ==========================================
    // 25. COPA 2026 (30)
    // ==========================================
    { palavra: "2026", dicas: ["Ano da Copa atual", "Sede dividida na América do Norte", "Primeira com 48 seleções"] },
    { palavra: "MEXICO", dicas: ["Sede da Copa 2026", "Primeiro país a sediar três Copas", "Estádio Azteca"] },
    { palavra: "CANADA", dicas: ["Sede da Copa 2026", "Primeira Copa masculina no país", "Cidades como Toronto e Vancouver"] },
    { palavra: "EUA", dicas: ["Sede da Copa 2026", "Teve a Copa de 1994", "Onde será disputada a grande final"] },
    { palavra: "VINI JR", dicas: ["Destaque brasileiro do Real Madrid", "Campeão da Champions", "Protagonista da seleção"] },
    { palavra: "RODRYGO", dicas: ["Atacante brasileiro do Real Madrid", "Conhecido como 'Raio'", "Menino da Vila"] },
    { palavra: "ENDRICK", dicas: ["Jovem promessa que foi para o Real Madrid", "Canhoto", "Revelação da base do Palmeiras"] },
    { palavra: "MUSIALA", dicas: ["Camisa 10 e joia da Alemanha", "Meia-atacante do Bayern de Munique", "Dribles curtos"] },
    { palavra: "BALON DOR", dicas: ["Prêmio da revista France Football", "Sonho dos craques da Copa", "Melhor jogador do mundo"] },
    { palavra: "FIFA", dicas: ["Entidade máxima do futebol", "Organiza a Copa do Mundo", "Sede em Zurique"] },
    { palavra: "CONMEBOL", dicas: ["Confederação sul-americana", "Organiza a Libertadores", "10 países"] },
    { palavra: "UEFA", dicas: ["Confederação europeia", "Organiza a Champions League", "55 países"] },
    { palavra: "CONCACAF", dicas: ["Confederação da América do Norte", "Organiza a Gold Cup", "Sede em Miami"] },
    { palavra: "DOMINGUEZ", dicas: ["Presidente da CONMEBOL", "Paraguaio", "Mandatário eleito"] },
    { palavra: "INFANTINO", dicas: ["Presidente da FIFA", "Suíço", "Mandatário da federação internacional"] },
    { palavra: "QATAR", dicas: ["Sede da Copa de 2022", "País do Oriente Médio", "Estádios modernos no deserto"] },
    { palavra: "RUSSIA", dicas: ["Sede da Copa de 2018", "País da Europa Oriental", "Cidades como Moscou e São Petersburgo"] },
    { palavra: "AFRICA DO SUL", dicas: ["Sede da Copa de 2010", "Primeira Copa na África", "Lembrada pelas vuvuzelas"] },
    { palavra: "BRASIL", dicas: ["Sede da Copa de 2014", "País do futebol", "Palco da final no Maracanã"] },
    { palavra: "ALEMANHA", dicas: ["Sede da Copa de 2006", "País europeu", "Copa lembrada pela excelente organização"] },
    { palavra: "COREIA", dicas: ["Sede da Copa de 2002", "País asiático", "Co-sede histórica com o Japão"] },
    { palavra: "JAPAO", dicas: ["Sede da Copa de 2002", "País asiático", "Palco do título do Penta do Brasil"] },
    { palavra: "FRANCA", dicas: ["Sede da Copa de 1998", "País europeu", "Campeã em casa em 1998"] },
    { palavra: "EUA", dicas: ["Sede da Copa de 1994", "País americano", "Final decidida nos pênaltis em Los Angeles"] },
    { palavra: "ITALIA", dicas: ["Sede da Copa de 1990", "País europeu", "Lembrada pelas noites mágicas"] },
    { palavra: "ARGENTINA", dicas: ["Sede da Copa de 1978", "País sul-americano", "Conquistou seu primeiro título em casa"] },
    { palavra: "MESSI", dicas: ["Maior jogador da Copa de 2022", "Campeão", "Ídolo mundial"] },
    { palavra: "MBAPPE", dicas: ["Destaque da final da Copa de 2022", "Fez um hat-trick na final", "Francês"] },
    { palavra: "NEYMAR", dicas: ["Craque brasileiro na última década", "Líder técnico de sua geração", "Maior artilheiro de gols oficiais da seleção"] },
    { palavra: "CRISTIANO RONALDO", dicas: ["Maior artilheiro de seleções do mundo", "Português", "Sua quinta Copa do Mundo foi em 2022"] },

    // ==========================================
    // 26. JOGOS DE FUTEBOL (15)
    // ==========================================
    { palavra: "FIFA", dicas: ["Antigo nome da famosa franquia de videogame da EA Sports", "Entidade máxima do futebol", "Simulador virtual"] },
    { palavra: "PES", dicas: ["Franquia Pro Evolution Soccer", "Antigo rival do FIFA nos videogames", "Criado pela Konami"] },
    { palavra: "GOL", dicas: ["Momento supremo do futebol", "Balançar a rede", "Ponto máximo da partida"] },
    { palavra: "BOLA", dicas: ["O objeto principal do esporte", "Formato esférico", "A Al Rihla e a Jabulani foram exemplos"] },
    { palavra: "BICICLETA", dicas: ["Chute acrobático no ar de costas para o gol", "Leônidas da Silva popularizou", "Plástica perfeita"] },
    { palavra: "FALTA", dicas: ["Infração cometida sobre o adversário", "Pode ser cobrada direto para o gol", "Barreira tenta bloquear"] },
    { palavra: "CARTAO", dicas: ["Item de advertência do árbitro", "Pode ser amarelo ou vermelho", "Exclui o jogador se for repetido"] },
    { palavra: "VAR", dicas: ["Árbitro de vídeo", "Tecnologia para revisar lances capitais", "Checa gols, cartões e impedimentos"] },
    { palavra: "CHUTEIRA", dicas: ["Calçado específico para o gramado", "Possui travas na sola", "Modelos famosos da Nike, Adidas e Puma"] },
    { palavra: "UNIFORME", dicas: ["Conjunto de camisa, calção e meiões", "Identidade visual do time em campo", "Manto sagrado"] },
    { palavra: "IMPEDIMENTO", dicas: ["Regra do futebol", "Atacante adiantado no momento do passe", "Assinalado pelo bandeirinha"] },
    { palavra: "ESCANTEIO", dicas: ["Cobrança de canto", "Bola sai pela linha de fundo tocada pelo defensor", "Chance de gol de cabeça"] },
    { palavra: "PENALTI", dicas: ["Tiro livre da marca de 11 metros", "Falta dentro da grande área", "Cobrança sem barreira"] },
    { palavra: "GOLEIRO", dicas: ["Única posição que pode usar as mãos na área", "Defende os chutes adversários", "Camisa 1"] },
    { palavra: "TECNICO", dicas: ["Treinador estratégico do time", "Comanda os jogadores da beira do gramado", "Monta a escalação"] },
    
    // JOGADORAS FEMININAS (5 mais conhecidas)
    { palavra: "MARTA", dicas: ["Maior jogadora da história do futebol feminino", "Brasileira", "Eleita seis vezes a melhor do mundo"] },
    { palavra: "FORMIGA", dicas: ["Lendária jogadora da seleção brasileira", "Meio-campo de incrível longevidade", "Disputou sete Copas do Mundo"] },
    { palavra: "CRISTIANE", dicas: ["Grande atacante da seleção brasileira", "Artilheira histórica em Olimpíadas", "Goleadora nata"] },
    { palavra: "DEBINHA", dicas: ["Atacante talentosa da seleção brasileira", "Muito habilidosa e veloz", "Destaque nos Estados Unidos"] },
    { palavra: "AMANDINHA", dicas: ["Considerada múltiplas vezes a melhor jogadora de futsal do mundo", "Cearense", "Habilidade espetacular"] },

        // TÉCNICOS FAMOSOS (adicionais)
    { palavra: "ANCELLOTTI", dicas: ["Técnico italiano multicampeão", "Comandou Real Madrid e Milan", "Especialista em Champions League"] },
    { palavra: "ZIDANE", dicas: ["Técnico francês", "3 Champions seguidas pelo Real Madrid", "Ex-jogador genial"] },
    { palavra: "PEP GUARDIOLA", dicas: ["Técnico espanhol", "Revolucionou o futebol com tiki-taka", "Multicampeão por Barcelona, Bayern e City"] },
    { palavra: "JURGEN KLOPP", dicas: ["Técnico alemão", "Conhecido pelo 'heavy metal football'", "Campeão da Champions pelo Liverpool"] },
    { palavra: "JOSE MOURINHO", dicas: ["Técnico português", "Conhecido como 'Special One'", "Campeão da Champions com Porto e Inter"] },
    { palavra: "TITE", dicas: ["Técnico brasileiro", "Comandou o Brasil em 2018 e 2022", "Multicampeão pelo Corinthians"] },
    { palavra: "RENATO GAUCHO", dicas: ["Técnico brasileiro", "Ídolo do Grêmio como jogador e técnico", "Campeão da Libertadores em 2017"] },
    { palavra: "ABEL FERREIRA", dicas: ["Técnico português", "Revolucionou o Palmeiras", "Bicampeão da Libertadores consecutiva"] },
    { palavra: "FELIPAO", dicas: ["Técnico brasileiro", "Campeão do mundo em 2002", "Conhecido como Felipão"] },
    { palavra: "MURICY", dicas: ["Técnico brasileiro", "Tricampeão brasileiro pelo São Paulo", "Estrategista"] },

        // NARRADORES E COMENTARISTAS FAMOSOS
    { palavra: "GALVAO", dicas: ["Maior narrador da história do Brasil", "Narrou Copas do Mundo", "Voz da Globo"] },
    { palavra: "JUNIOR", dicas: ["Comentarista e ex-jogador", "Voz da Globo", "Análise tática"] },
    { palavra: "CASAGRANDE", dicas: ["Comentarista polêmico", "Ex-jogador", "Voz forte"] },

        // PREMIAÇÕES E TÍTULOS
    { palavra: "BOLA DE OURO", dicas: ["Prêmio da France Football", "Melhor jogador do mundo", "Messi e Ronaldo dominaram"] },
    { palavra: "CHUTEIRA DE OURO", dicas: ["Prêmio para o maior artilheiro da Europa", "Messi tem mais", "Lewandowski também venceu"] },
    { palavra: "LUVAS DE OURO", dicas: ["Prêmio para o melhor goleiro do mundo", "Neuer e Buffon venceram", "Alisson também ganhou"] },
    { palabra: "FIFA THE BEST", dicas: ["Prêmio da FIFA", "Melhor jogador do mundo", "Votação anual"] },
    { palavra: "PUSKAS", dicas: ["Prêmio para o gol mais bonito do ano", "Homenagem a Puskás", "Neymar e Cristiano Ronaldo venceram"] },

    // TORNEIOS INTERNACIONAIS
    { palavra: "MUNDIAL", dicas: ["Torneio de clubes da FIFA", "Campeão do mundo", "Disputado anualmente"] },
    { palavra: "LIBERTADORES", dicas: ["Maior torneio de clubes da América do Sul", "Organizado pela CONMEBOL", "Mais importante do continente"] },
    { palavra: "SULAMERICANA", dicas: ["Segundo torneio mais importante da América do Sul", "Organizado pela CONMEBOL", "Equivalente à Europa League"] },
    { palavra: "PREMIER LEAGUE", dicas: ["Campeonato inglês", "Mais rico do mundo", "20 clubes"] },
    { palavra: "LA LIGA", dicas: ["Campeonato espanhol", "Real Madrid e Barcelona dominam", "20 clubes"] },
    { palavra: "SERIE A", dicas: ["Campeonato italiano", "Conhecido como Calcio", "20 clubes"] },
    { palabra: "BUNDESLIGA", dicas: ["Campeonato alemão", "Bayern Munich domina", "18 clubes"] },
    { palabra: "LIGUE 1", dicas: ["Campeonato francês", "PSG domina", "20 clubes"] },
    { palabra: "BRASILEIRAO", dicas: ["Campeonato brasileiro", "Série A", "20 clubes"] },
    { palavra: "COPA DO BRASIL", dicas: ["Torneio mata-mata brasileiro", "Mais de 90 clubes", "Hexacampeão Cruzeiro"] }
    
];
